# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eduardo Espadeiro
title_separator: "|"
name: Eduardo Espadeiro
email: eduardo.espadeiro@tecnico.ulisboa.pt
description: >-
  Hey, I’m Eduardo Espadeiro, a Developer and Student.
  I love programming and I’m currently studying
  Computer Science and Engineering at Instituto
  Superior Técnico in Lisbon.

baseurl: ""
url: "https://eduespadeiro.com"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"
plugins:
  - jekyll-feed

author:
  name: "Eduardo Espadeiro"
  avatar: "/assets/images/eduardo.png"
  bio: "Computer Science and Engineering Student"
  location: "Évora, Portugal"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EdSwordsmith"
    - label: "Itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://edswordsmith.itch.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/EdSwordsmith"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eduardo-espadeiro"


timezone: Europe/Lisbon
paginate: 5
locale: "en"
title_separator: "|"
breadcrumbs: true
search: true
permalink: /:categories/:title/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      show_date: true
      author_profile: false
      share: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

collections:
  projects:
    output: true
    permalink: /:collection/:path/

include:
  - _pages/
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
