backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: src/posts
    create: true
    identifier_field: title
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: "Featured Image", widget: image }
      - { name: body, label: Body, widget: markdown }
  
  - name: projects
    label: Project
    folder: src/projects
    create: true
    extension: yml
    identifier_field: title
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: "Featured Image", widget: image }
      - { name: techs, label: Techs, widget: list }
      - { name: code, label: "Code", required: false }
      - { name: projectUrl, label: "Project Url" }
